package com.nirmalkandel.paylog.quicknote

import android.appwidget.AppWidgetManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import org.json.JSONObject

/** Asks the home-screen widget to redraw; its JS task fetches the new month total. */
internal object Widgets {
  fun refresh(context: Context) {
    val app = context.applicationContext
    // Provider class generated by react-native-android-widget for the "QuickNote" widget.
    val provider = ComponentName(app.packageName, "${app.packageName}.widget.QuickNote")
    val ids = try {
      AppWidgetManager.getInstance(app).getAppWidgetIds(provider)
    } catch (e: Exception) {
      return
    }
    if (ids.isEmpty()) return
    app.sendBroadcast(
      Intent(AppWidgetManager.ACTION_APPWIDGET_UPDATE)
        .setComponent(provider)
        .putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids),
    )
  }
}

internal object Notes {
  /** "Saved ₹250 · Food · lunch" from the quick-add (or preview) response. */
  fun describe(json: JSONObject): String {
    val kind = if (json.optString("kind") == "income") "income " else ""
    val parts = mutableListOf("Saved $kind${json.optString("amount")}", json.optString("category"))
    json.optString("description").takeIf { it.isNotBlank() }?.let { parts += it }
    val whenText = json.optString("when")
    if (whenText.isNotBlank() && whenText != "today") parts += whenText
    return parts.filter { it.isNotBlank() }.joinToString(" · ")
  }

  fun lines(text: String): List<String> =
    text.split('\n').map { it.trim() }.filter { it.isNotEmpty() }.take(10)
}
